[project]
name = "r2agent"
version = "0.3.3"
description = "Automate radare2 workflows through autonomous agents."
authors = [
    {name = "Marcel Alexandru Nitan"}
]
license = {text = "MIT"}
requires-python = ">=3.10,<4.0"
dependencies = [
    "openai-agents[litellm] (>=0.8.0,<0.9.0)",
    "pydantic (>=2.0.0)",
    "appdirs (>=1.4.4)",
    "pyyaml (>=6.0.0)",
    "r2pipe (>=1.9.4)"
]

[project.scripts]
r2a = "r2agent.__main__:main"

[tool.poetry]
packages = [{include = "r2agent"}]
include = ["r2agent/prompts/*.txt"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
